### ISSUE TITLE
unable to connect using websocket

### ISSUE THREAD

**Issue by Fiekers** [akasamq/akasa#5]
Hi，
The following error occurs when using websocket connection:

![error1](https://github.com/akasamq/akasa/assets/28997868/58b4e418-b798-4d88-897c-436d40e7b874)

The configuration file is as follows: 
`
listeners:
  mqtt:
    addr: 0.0.0.0:1883
    proxy_mode: null
  mqtts: null
  ws:
    addr: 0.0.0.0:8083
    proxy_mode: null
  wss: null
auth:
  enable: false
  password_file: test.yml
scram_users:
  user:
    hashed_password: 2a2a2a
    iterations: 4096
    salt: 73616c74
sasl_mechanisms:
  - SCRAM-SHA-256
check_v310_client_id_length: false
shared_subscription_mode: Random
max_allowed_qos: 2
inflight_timeout: 15
max_inflight_client: 10
max_inflight_server: 10
max_in_mem_pending_messages: 256
max_in_db_pending_messages: 65536
min_keep_alive: 10
max_keep_alive: 65535
multiple_subscription_id_in_publish: false
max_session_expiry_interval: 4294967295
max_packet_size_client: 268435460
max_packet_size_server: 268435460
topic_alias_max: 65535
retain_available: true
shared_subscription_available: true
subscription_id_available: true
wildcard_subscription_available: true
hook:
  enable_before_connect: true
  enable_after_connect: true
  enable_publish: true
  enable_subscribe: true
  enable_unsubscribe: true
`
OS:
Linux fan 6.1.0-13-amd64 Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux

**Comment by TheWaWaR** [comment]
Which MQTT client/sdk are you using?

**Comment by TheWaWaR** [comment]
@Fiekers 
Fix in https://github.com/akasamq/akasa/commit/1ef96ac6911f931d66df070ec472a40651221206 , you can now have a try.
